### ISSUE TITLE
train on llff flower scene

### ISSUE THREAD

**Issue by that-liu** [nianticlabs/diffusionerf#19]
#!/bin/bash

mkdir ./runs/
python -m main_nerf /data3/liuyu/nerf_llff_data/flower/\
    --mode blender \
    --upsample_steps 128 \
    --num_rays 1024 \
    --max_ray_batch 1024 \
    --mode llff \
    --downsample_val 8 \
    --reg_ramp_start_step 3000 \
    --reg_ramp_finish_step 8000 \
    --iters 10000 \
    --min_near 0.2 \
    --spread_loss_strength 1.5e-5 \
    --num_train 3 \
    --use_frustum_reg \
    --patch_weight_start 0.2 \
    --patch_weight_finish 0.2 \
    --normalise_diffusion_losses \
    --patch_regulariser_path models/rgbd-patch-diffusion.pt \
    --frustum_regularise_patches \
    --apply_geom_reg_to_patches \
    --downsample_train 8 \
    --patch_reg_start_step 0 \
    --workspace ./runs/train/3_poses/flower/
I used this command and the following error occurred in the flower scene of training llff.:
==> Start Training Epoch 1, lr=0.010000 ...
  0% 0/201 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/data1/liuyu/miniconda3/envs/diffusionerf/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/data1/liuyu/miniconda3/envs/diffusionerf/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data1/liuyu/MPI/diffusionerf/main_nerf.py", line 145, in <module>
    run(opt)
  File "/data1/liuyu/MPI/diffusionerf/main_nerf.py", line 122, in run
    trainer.train(train_loader, valid_loader, max_epoch)
  File "/data1/liuyu/MPI/diffusionerf/nerf/utils.py", line 657, in train
    self.train_one_epoch(train_loader)
  File "/data1/liuyu/MPI/diffusionerf/nerf/utils.py", line 776, in train_one_epoch
    preds, truths, loss, extra_outputs = self.train_step(data)
  File "/data1/liuyu/MPI/diffusionerf/nerf/utils.py", line 412, in train_step
    outputs = self.model.render(rays_o, rays_d, staged=False, bg_color=bg_color, perturb=True, force_all_rays=False, **vars(self.opt))
  File "/data1/liuyu/MPI/diffusionerf/nerf/renderer.py", line 370, in render
    results = _run(rays_o, rays_d, **kwargs)
  File "/data1/liuyu/MPI/diffusionerf/nerf/renderer.py", line 129, in run
    z_vals = perturb_z_vals(z_vals)
  File "/data1/liuyu/MPI/diffusionerf/nerf/rendering_helpers.py", line 31, in perturb_z_vals
    assert (deltas >= 0).all()
AssertionError
  0% 0/201 [00:00<?, ?it/s]

**Comment by XLR-man** [comment]
Hi I also get the same problem. Did you fix it? @that-liu
